// Generated from iOS/SpenDrop/OCR/MerchantDetector.swift (knownMerchants) — keep in sync.
import type { CategoryId } from "@/lib/domain/types";

export interface KnownMerchant { name: string; keywords: string[]; category: CategoryId; ambiguous?: boolean }

export const KNOWN_MERCHANTS: KnownMerchant[] = [
  { name: "McDonald's", keywords: ["mcdonald's", "mcdonalds", "mcd", "golden arches"], category: "Food" },
  { name: "KFC", keywords: ["kfc", "kentucky fried chicken", "qsr stores"], category: "Food" },
  { name: "Starbucks", keywords: ["starbucks", "berjaya starbucks"], category: "Food" },
  { name: "Zus Coffee", keywords: ["zus coffee", "zus"], category: "Food" },
  { name: "Tealive", keywords: ["tealive", "loob holding"], category: "Food" },
  { name: "Subway", keywords: ["subway"], category: "Food" },
  { name: "FamilyMart", keywords: ["familymart", "family mart", "ql maxincome"], category: "Food" },
  { name: "Burger King", keywords: ["burger king", "cosmo restaurants"], category: "Food" },
  { name: "Pizza Hut", keywords: ["pizza hut"], category: "Food" },
  { name: "Nando's", keywords: ["nando's", "nandos"], category: "Food" },
  { name: "Texas Chicken", keywords: ["texas chicken"], category: "Food" },
  { name: "Marrybrown", keywords: ["marrybrown"], category: "Food" },
  { name: "The Coffee Bean", keywords: ["coffee bean", "cbtl"], category: "Food" },
  { name: "Nasi Kandar Pelita", keywords: ["nasi kandar pelita", "restoran nasi kandar pelita", "pelita nasi kandar"], category: "Food" },
  { name: "Grab", keywords: ["grabcar", "grab ride", "grab taxi", "grab driver", "myteksi"], category: "Transport" },
  { name: "GrabFood", keywords: ["grabfood", "grab food"], category: "Food" },
  { name: "Grab", keywords: ["grab"], category: "Transport", ambiguous: true },
  { name: "Foodpanda", keywords: ["foodpanda", "food panda", "delivery hero"], category: "Food" },
  { name: "Shell", keywords: ["shell petrol", "shell station", "shell"], category: "Transport" },
  { name: "Petronas", keywords: ["petronas", "mesra"], category: "Transport" },
  { name: "Caltex", keywords: ["caltex"], category: "Transport" },
  { name: "BHPetrol", keywords: ["bhpetrol", "bhp"], category: "Transport" },
  { name: "Touch 'n Go RFID", keywords: ["tng rfid", "rfid toll", "plus expressways"], category: "Transport" },
  { name: "Rapid KL", keywords: ["rapid kl", "prasarana", "mrt", "lrt"], category: "Transport" },
  { name: "MYDIN", keywords: ["mydin"], category: "Groceries" },
  { name: "7-Eleven", keywords: ["7-eleven", "7 eleven", "7eleven", "seven eleven"], category: "Groceries" },
  { name: "Lotus's", keywords: ["lotus's", "lotuss", "tesco"], category: "Groceries" },
  { name: "Jaya Grocer", keywords: ["jaya grocer", "trendcell"], category: "Groceries" },
  { name: "Village Grocer", keywords: ["village grocer", "the food purveyor"], category: "Groceries" },
  { name: "Giant", keywords: ["giant hypermarket", "giant supermarket", "gch retail"], category: "Groceries" },
  { name: "Aeon", keywords: ["aeon co", "aeon big", "aeon"], category: "Groceries" },
  { name: "99 Speedmart", keywords: ["99 speedmart", "speedmart"], category: "Groceries" },
  { name: "KK Super Mart", keywords: ["kk super mart", "kk mart"], category: "Groceries" },
  { name: "MR. D.I.Y.", keywords: ["mr. d.i.y.", "mr diy", "mrdiy"], category: "Shopping" },
  { name: "CU Mart", keywords: ["cu mart", "cu convenient store"], category: "Groceries" },
  { name: "Shopee", keywords: ["shopee", "shopeepay"], category: "Shopping" },
  { name: "Lazada", keywords: ["lazada"], category: "Shopping" },
  { name: "TikTok Shop", keywords: ["tiktok shop", "tiktok"], category: "Shopping" },
  { name: "Uniqlo", keywords: ["uniqlo"], category: "Shopping" },
  { name: "Zara", keywords: ["zara"], category: "Shopping" },
  { name: "Watsons", keywords: ["watsons", "watson's"], category: "Health" },
  { name: "Guardian", keywords: ["guardian"], category: "Health" },
  { name: "Caring Pharmacy", keywords: ["caring pharmacy", "caring"], category: "Health" },
  { name: "TNB", keywords: ["tenaga nasional", "tnb"], category: "Bills" },
  { name: "Air Selangor", keywords: ["air selangor", "syabas"], category: "Bills" },
  { name: "Unifi", keywords: ["unifi", "telekom malaysia", "tm"], category: "Bills" },
  { name: "Maxis", keywords: ["maxis", "hotlink"], category: "Bills" },
  { name: "CelcomDigi", keywords: ["celcomdigi", "celcom", "digi"], category: "Bills" },
  { name: "U Mobile", keywords: ["u mobile", "umobile"], category: "Bills" },
  { name: "Netflix", keywords: ["netflix"], category: "Subscription" },
  { name: "Spotify", keywords: ["spotify"], category: "Subscription" },
  { name: "Apple Services", keywords: ["apple.com/bill", "itunes.com/bill", "apple bill"], category: "Subscription" },
  { name: "Google Play", keywords: ["google play", "google *"], category: "Subscription" },
  { name: "GSC Cinemas", keywords: ["gsc cinemas", "golden screen cinemas", "gsc"], category: "Entertainment" },
  { name: "TGV Cinemas", keywords: ["tgv cinemas", "tgv"], category: "Entertainment" },
];
